:doctype: book

= Documentation
Project Reactor reference documentation, code samples, and Javadoc.

++++
include::nav.html[]
include::breadcrumb.html[tags="pre"]
include::breadcrumb.html[tags="post"]
++++

<<getting-started,Getting Started>>:: How to get going quickly with Reactor.
link:/docs/reference/[Reference]:: Reference documentation covering the basic components of Reactor as well as more advanced concepts.
link:/docs/api/[Javadoc]:: Documentation on the Reactor API.

[[introduction]]
== What is Reactor?

Reactor is a foundational library for building reactive fast-data applications on the JVM. You can use any JVM langauge, from Java 7 or Java 8, to Scala, Groovy, or even Nashorn JavaScript. It's designed to be fast and efficient to enable you to write asynchronous applications that can manage extremely high workloads with very little overhead. It builds on the extreme throughput capabilities of the https://github.com/LMAX-Exchange/disruptor[Disruptor RingBuffer] to achieve throughput in the 10's of _millions_ of operations per second (even up to 100's if you have enough hardware horsepower).footnoteref:[benchmark,Reactor microbenchmarks are maintained in a https://github.com/reactor/reactor-benchmark[separate GitHub repository]]

=== Reactive Streams

The Reactor team are core contributors to the https://github.com/reactive-streams/reactive-streams[Reactive Streams Specification]. Reactive Streams is "an initiative to provide a standard for asynchronous stream processing with non-blocking back pressure on the JVM."

There are certain characteristics of a system that "speaks" Reactive Streams beyond just using a common, shared API. The components inside Reactor's `Stream` actions behave in a predictable way since they implement the Reactive Streams standard. This is a type of inter-operability among implementations that goes far beyond a common set of interfaces. In fact, Reactive Streams implementations can largely be depended upon to Just Work(TM).

[[getting-started]]
== Getting Started

To add Reactor to an existing project, you just need to include the appropriate artifact. The basic components of Reactor like `EventBus` and `Stream` are in the `reactor-core` artifact. Additional functionality is in the `reactor-net`, `reactor-groovy`, and `reactor-logback` modules.

[pass]
<div class="ui segment">

.build.gradle
[source,groovy]
----
ext {
  reactorVersion = '2.0.0.M2'
}

repositories {
  // maven { url 'http://repo.spring.io/libs-milestone' } // <1>
  // maven { url 'http://repo.spring.io/libs-snapshot' } // <2>
}

dependencies {
  compile "io.projectreactor:reactor-core:$reactorVersion"
}
----
<1> Uncomment to use a milestone version.
<2> Uncomment to use a snapshot version.

[pass]
</div>

Now that you've added the Reactor library to your project, you can start using the `Stream` class to perform high-volume, low-latency, asynchronous work. It's really almost deceptively simple. Here's a completle Hello World to get you started.

[pass]
<div class="ui segment">

.ReactorHelloWorld.java
[source,java]
----
import reactor.Environment;
import reactor.rx.Streams;
import reactor.rx.stream.Broadcaster;

public class ReactorHelloWorld {
  public static void main(String... args) throws InterruptedException {
    Environment.initialize(); // <1>

    Broadcaster<String> sink = Streams.broadcast(Environment.get()); // <2>

    sink.dispatchOn(Environment.cachedDispatcher()) // <3>
        .map(String::toUpperCase) // <4>
        .consume(s -> System.out.printf("s=%s%n", s)); // <5>

    sink.onNext("Hello World!"); // <6>

    Thread.sleep(500); // <7>
  }
}
----
<1> If using Reactor's static `Environment` instance, it must be initialized before calling `Environment.get()`. You could also do this in a `static {}` block.
<2> A `Broadcaster` is a special kind of `Stream` that allows publishing of values.
<3> Dispatch downstream tasks onto a load-balanced `Dispatcher`.
<4> Transform input to upper-case and implicitly broadcast downstream.
<5> Consume the transformed input and print to STDOUT.
<6> Publish a value into the `Stream`.
<7> Block the `main` thread until work on other threads is complete, otherwise we won't see any output.

[pass]
</div>

[[dispatching]]
=== Dispatching is Fundamental

In Reactor, you'll find a lot of references to "dispatching". Reactor takes executing tasks very seriously, so it's considered a first-class concern in the framework. It might be tempting to say "but I don't want to have to worry about which thread my tasks are executed on." Having dispatching as a first-class concern, however, means you don't have to worry about blocking in recursive asynchronous tasks because the `Dispatcher` implementation will manage queueing and execution for you.