:doctype: book

= Reference
In-depth reference documentation for most components in Reactor.

++++
include::../nav.html[]
include::../breadcrumb.html[tags="pre"]
  <div class="active section">Reference</div>
include::../breadcrumb.html[tags="post"]
++++

== Streaming

[horizontal]
<<streams.adoc#basics,Basics>>::
Using a `Stream` and the Reactive Streams standard to compose pipelines.
<<streams.adoc#work-queue,Work Queue>>::
Using a `Stream` as a work queue for concurrent, parallel work.

== Event Bus

[horizontal]
<<event-bus.adoc#publish-subscribe,Publish/Subscribe>>::
Using an `EventBus` to publish and respond to events using Publish/Subscribe.
<<event-bus.adoc#request-reply,Request/Reply>>::
Using an `EventBus` to publish and respond to events using Request/Reply.

== Disruptor RingBuffer-powered Reactive Streams Processor

[horizontal]
<<processor.adoc#basics,Basics>>::
Using a Disruptor RingBuffer-based `Processor` to publish and respond to events at extremely high throughput.

== TCP and HTTP

[horizontal]
<<tcp.adoc#basics,Basics>>:: Using Reactor's TCP support to create high-performance TCP clients and servers.
<<http.adoc#basics,Basics>>:: Using Reactor's HTTP support to create high-performance HTTP clients and servers.

== Spring Support

[horizontal]
<<spring.adoc#basics,Basics>>::
Writing Reactor applications that are deployed inside a Spring `ApplicationContext`.

== Example Applications

[horizontal]
https://github.com/reactor/reactor-quickstart[Quickstart]::
An example application showing several ways to use basic components in Reactor.
https://github.com/reactor/reactor-samples[Samples]::
A simple sample application that demonstrates Reactor functionality in JUnit tests.
https://github.com/SpringOne2GX-2014/reactive-geocoder/[reactive-geocoder]::
A more advanced example application that combines Reactor with the Ratpack web framework.