name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
permissions: read-all
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0 #for spotless ratchet
      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@add58192d1c6f4603dc6821e8616f251e2782884
      - name: license header
        if: ${{ github.event_name == 'pull_request' }}
        run: ./gradlew spotlessCheck -PspotlessFrom=origin/${{ github.base_ref }}
      - name: tests
        run: ./gradlew check -x spotlessCheck
