name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
permissions: {}
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
        with:
          fetch-depth: 0 #for spotless ratchet
      - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: license header
        if: ${{ github.event_name == 'pull_request' }}
        run: ./gradlew spotlessCheck -PspotlessFrom=origin/${{ github.base_ref }}
      - name: tests
        run: ./gradlew check -x spotlessCheck
