name: DEPLOY

on:
  workflow_dispatch:
    permissions:
      teams:
        - 'reactor/team'

permissions: {}

env:
  GROUP_NAME: ${{ secrets.AZURE_GROUP_NAME_ASA }}
  SERVICE_NAME: ${{ secrets.AZURE_SERVICE_NAME_ASA }}
  APP_NAME: ${{ secrets.AZURE_APP_NAME_ASA }}
  JAR_PATH: ${{ github.workspace }}/build/libs/projectreactor-home.jar

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      NEWDEPLOYMENT: ${{ steps.deploy.outputs.NEWDEPLOYMENT }}
      ACTIVEDEPLOYMENT: ${{ steps.deploy.outputs.ACTIVEDEPLOYMENT }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build
        run: ./gradlew build -x spotlessCheck
      - name: Login Via Azure CLI
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43 # v3.0.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SPRING_ASA }}
      - name: Set up Azure Spring Extension
        run: az extension add --name spring
      - name: Create app
        run: |
          az spring app create \
          --name ${{ env.APP_NAME }} \
          --resource-group ${{ env.GROUP_NAME }} \
          --instance-count 2 \
          --assign-endpoint true \
          --service ${{ env.SERVICE_NAME }}
        continue-on-error: true
      - name: Deploy
        run: |
          az spring app deploy \
            --name ${{ env.APP_NAME }} \
            --service ${{ env.SERVICE_NAME }} \
            --resource-group ${{ env.GROUP_NAME }} \
            --artifact-path ${{env.JAR_PATH}} \
            --runtime-version Java_21 \
            --jvm-options='-Xmx1g -Xms1g'
